version: "3"

services:
    filebeat:
        image: docker.elastic.co/beats/filebeat:7.9.3
        container_name: mifilebeat
        volumes:
            - /home/ubuntu/environment/curso/filebeat/apache.log:/tmp/apache.log
            - /home/ubuntu/environment/curso/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
